/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_CDLLLib */

#ifndef _Included_model_CDLLLib
#define _Included_model_CDLLLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_CDLLLib
 * Method:    BarnsleyFernAlgorithm
 * Signature: ([FIFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_model_CDLLLib_BarnsleyFernAlgorithm
  (JNIEnv *, jobject, jfloatArray, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
